### ISSUE TITLE
How can I test go?

### ISSUE THREAD

**Issue by Strke** [fuzz4all/fuzz4all#3]
after running `./scripts/full_run.sh go`, I don't find the file `./scripts/build_go_coverage.sh`, so maybe I think 
1、set the environment variables
```
export GOROOT=/home/go
export PATH=$PATH:$GOROOT/bin
```
2、then run the script
```
python tools/coverage/GO/collect_coverage.py --folder outputs/full_run/go --interval 10
```
Is it right to do this？

**Comment by brutalsavage** [comment]
Yes, that should be how to collect coverage. One thing to check is that your Go version supports `Covdata` such that you can collect coverage. You can check the detailed command in `tools/coverage/GO/collect_coverage.py` and run some simple tests to check.

**Comment by Strke** [comment]
Thank you, I have obtained the coverage of go.
but now I have encountered a new problem. How to obtain the coverage of java? I ran the program `collect_coverage.py` and found that there is no `java_whitelist` file.
![image](https://github.com/fuzz4all/fuzz4all/assets/61811634/3ec98c69-30fe-4420-80cd-9c4cb92ba08e)

**Comment by brutalsavage** [comment]
Hi, the java coverage collection system is actually build on top of the hephaestus fuzzing tool. That is also one reason the java coverage collection is a bit under developed in the current artifact since it requires some build setups. I recommend following the hephaestus tool (which we directly used for coverage collection). 

You can find their artifact here: https://zenodo.org/records/6410434 (you can find java_whitelist in there for example)

Hope this can help

**Comment by Strke** [comment]
Thanks, I'll try it！
